export const GET_INGREDIENTS = 'GET_INGREDIENTS'
export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT'
export const GET_INGREDIENTS_FAILED = 'GET_INGREDIENTS_FAILED'