export const GET_INGREDIENTS = 'GET_INGREDIENTS'
export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT'
export const GET_INGREDIENTS_FAILED = 'GET_INGREDIENTS_FAILED'

export const PUSH_ORDER = 'PUSH_ORDER'
export const PUSH_ORDER_SUCCESS = 'PUSH_ORDER_SUCCESS'
export const PUSH_ORDER_FAILED = 'PUSH_ORDER_FAILED'
export const PUSH_ORDER_START = 'PUSH_ORDER_START'